name: "Upload to CurseForge"
on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Release downloader"
      id: download
      # You may pin to the exact commit or the version.
      # uses: robinraju/release-downloader@d6de084c58345d09b017e22701dbcf26977cfd14
      uses: robinraju/release-downloader@v1.6
      with:
        # A flag to choose between latest release and remaining releases
        latest: true
    - name: "Substring"
      id: substring
      uses: web3j/substr-action@v1.2
      with:
        value: ${{ steps.download.outputs.tag_name }}
        start: '1'
    - name: "Upload to CurseForge"
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "build/libs/InstantStone-${{ steps.substring.outputs.result }}-SNAPSHOT.jar"
        game_endpoint: "minecraft"
        game_versions: "Minecraft 1.19:1.19.1:1.19.2:1.19.3,Java 17,Forge"
        project_id: "695517"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
