name: "Upload to CurseForge"
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Release downloader"
      id: download
      # You may pin to the exact commit or the version.
      # uses: robinraju/release-downloader@d6de084c58345d09b017e22701dbcf26977cfd14
      uses: robinraju/release-downloader@v1.6
      with:
        # A flag to choose between latest release and remaining releases
        latest: true
    - name: "Upload to CurseForge"
      uses: itsmeow/curseforge-upload@v3
      with:
        release_type: "release"
        file_path: "InstantStone-${{ steps.download.outputs.tag_name }}-SNAPSHOT.jar"
        display_name: "InstantStone v${{ steps.download.outputs.tag_name }}"
        game_endpoint: "minecraft"
        game_versions: "Minecraft 1.19:1.19.3,Java 17,Forge"
        project_id: "695517"
        changelog_type: "markdown"
        changelog: "[Changelog available on GitHub](https://github.com/Dwight-Studio/InstantStone/releases)"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
